# Generated by Django 5.0.1 on 2024-03-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userspage", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
