# Generated by Django 5.0.1 on 2024-02-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.FileField(null=True, upload_to="static/uploads"),
        ),
    ]
